### ISSUE TITLE
Handle displaying 401 API errors

### ISSUE THREAD

**Issue by kumar303** [mozilla/addons-frontend#1527]
### Describe the problem and steps to reproduce it:
Create a 401 API error in the UI (not on the server). This would do it:
* Go to an add-on page
* make sure you're not logged in
* Click on a star to add a rating

### What happened?

The `SET_ERROR` action payload looks like:
````
{
  response: {
    apiURL: "http://olympia.dev/api/v3/addons/addon/food-truck-pie/reviews/?lang=en-US",
    data: {
      detail: "Authentication credentials were not provided."
    },
    status: 401,
  }
}
````

````
error TypeError: val.forEach is not a function
    at http://127.0.0.1:3001/amo-0236d939da573fb964ad.js:78017:14
    at Array.forEach (native)
    at http://127.0.0.1:3001/amo-0236d939da573fb964ad.js:78015:41
    at getMessagesFromError (http://127.0.0.1:3001/amo-0236d939da573fb964ad.js:78033:8)
    at errors (http://127.0.0.1:3001/amo-0236d939da573fb964ad.js:78049:20)
    at combination (http://127.0.0.1:3001/amo-0236d939da573fb964ad.js:33022:30)
    at i (<anonymous>:1:18467)
    at u (<anonymous>:1:18753)
    at <anonymous>:1:21682
    at Object.dispatch (http://127.0.0.1:3001/amo-0236d939da573fb964ad.js:32444:23)
````

### What did you expect to happen?

* no stack trace
* error shown at the top of the page

### Anything else we should know?

Eventually we should support prompting for log in when this happens but until then the error reporter should at least work

**Comment by tofumatt** [comment]
I think I fixed this in #1685; will double-check.

**Comment by kumar303** [comment]
Sadly, no, that patch didn't fix it but I think it's the same problem (something is trying to iterate over the response).

I think I'm getting a different stack trace for it now:
````
webpack:///./src/core/reducers/errors.js:20

Uncaught (in promise) TypeError: val.forEach is not a function
    at http://127.0.0.1:3001/amo-7822798f3661faa94ad3.js:90197:14
    at Array.forEach (native)
    at http://127.0.0.1:3001/amo-7822798f3661faa94ad3.js:90195:41
    at getMessagesFromError (http://127.0.0.1:3001/amo-7822798f3661faa94ad3.js:90213:8)
    at errors (http://127.0.0.1:3001/amo-7822798f3661faa94ad3.js:90229:20)
    at combination (http://127.0.0.1:3001/amo-7822798f3661faa94ad3.js:31695:30)
    at dispatch (http://127.0.0.1:3001/amo-7822798f3661faa94ad3.js:31118:23)
    at ErrorHandler.dispatch (http://127.0.0.1:3001/amo-7822798f3661faa94ad3.js:90571:30)
    at ErrorHandler.handle (http://127.0.0.1:3001/amo-7822798f3661faa94ad3.js:79634:13)
    at http://127.0.0.1:3001/amo-7822798f3661faa94ad3.js:61694:21
````

**Comment by kumar303** [comment]
This was bothering me so I made a patch. r? https://github.com/mozilla/addons-frontend/pull/1818
