### ISSUE TITLE
"Login to rate this extension" button is working only at second click

### ISSUE THREAD

**Issue by vcarciu** [mozilla/addons-frontend#1904]
Steps to trreproduce:
1.On Android , log in to AMO-dev and be sure that you are logged out
2.Open any add-on and go to review section
3.Press the _Login to rate this extension_ button

Expected results:
Login page is opened

Actual results:
You have to press the _Login to rate this extension_ button twice

NOTES:
Reproducible on many devices , every time

Please see video for the issue(observe that the button was pressed twice and FXA page started to load only second time) : 
![secondclick](https://cloud.githubusercontent.com/assets/1583842/23313305/d7cb40b4-fac5-11e6-8b1e-f3ec28753ebc.gif)

**Comment by kumar303** [comment]
I can't reproduce it using Android touch emulation. I'll fire up a real device and try it.

**Comment by tofumatt** [comment]
It’s a thing that happens on Firefox for Android a fair bit; I see it and so does Sarah on a lot of sites… but I see it for what seem like regular links too. It might be a browser bug.

**Comment by tofumatt** [comment]
I think #2133 may have fixed this as well, as we think it's click-vs-touch event related. Going to close this as fixed by #2133, but reopen if I'm wrong 😄

**Comment by vcarciu** [comment]
This is still reproducible : 
![reopening](https://cloud.githubusercontent.com/assets/1583842/24258272/e6eebec8-0ff5-11e7-9e52-d7f477c45911.gif)

**Comment by tofumatt** [comment]
Out of curiosity, can you click and wait a bit longer? I’m wondering if the click is working but it’s just the lack of indication is the issue.

**Comment by vcarciu** [comment]
A long click will not work at all , no matter how much longer clicks are performed

**Comment by tofumatt** [comment]
Sorry, I mean if you click and then wait longer than normal. Even after five seconds will it still not load?

**Comment by vcarciu** [comment]
No , a longer click will not work

**Comment by muffinresearch** [comment]
@vcarciu can you provide details of device and the precise version of FF Android you are using?

Do device console logs show anything at all?

**Comment by kumar303** [comment]
@vcarciu one thing that would really help us understand this issue is to try the following:

- Make sure you are logged out
- Load an add-on detail page, scroll to the rating section
- Tap the Login to rate this extension button once and release your finger
- Wait for 5 seconds

Does it load while you are waiting?

**Comment by vcarciu** [comment]
@muffinresearch : 
- Device : Samsung Galaxy S7 Edge, Android version 7.0 , FF 55.0a1
- Console logs are not showing anything for me

@kumar303 
- It will not load at all after releasing my finger first time no matter how much time I am waiting

**Comment by kumar303** [comment]
ok, thanks.

**Comment by muffinresearch** [comment]
@vcarciu - are you still seeing this? I think the best next step would be to add logging to the button and then see if we are seeing the clicks as expected?

**Comment by vcarciu** [comment]
@muffinresearch : Yes, issue is still reproducible. What should I exactly do in order to provide more info on these clicks?

**Comment by muffinresearch** [comment]
@kumar303 @tofumatt can either of you reproduce this on Android devices?

**Comment by tofumatt** [comment]
Yes, actually, just tried. The first tap focuses the element but doesn't seem to fire the click event. I'll have a look, definitely frustrating.

**Comment by tofumatt** [comment]
Finally figured this one out, it was a weird one. Seems having hover styles applied to an `<a>` tag like the one created here gets mobile browsers to show the hover state on first tap. It certainly reads like https://css-tricks.com/annoying-mobile-double-tap-link-issue/.

Oddly a href tag works, so I'll include a requirement for a `href` value if no `to` value is set for buttons going forward.

**Comment by vcarciu** [comment]
This issue is still reproducible but with a strange pattern : 
FF Release : intermittently reproducible in about 50% of cases(tested on multiple devices like Samsung Galaxy S7, Google Pixel)
FF Nightly : 100% reproducible on all devices tested

I can confirm that the first tap focuses the element, but the click action is not triggered

**Comment by kumar303** [comment]
@tofumatt hey, that was an awesome find!

It looks like [@media pointer](http://caniuse.com/#feat=css-media-interaction) isn't supported in Firefox yet though. The [tracking bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1035774) suggests this as a workaround:

```css
@media (-moz-touch-enabled: 1), (pointer: coarse) {
  // Rules for touch screens
}
```

**Comment by tofumatt** [comment]
Super weirdly I tested this on my Android and it worked. But yeah, I'll go for that selector instead 🤷‍♀️

**Comment by vcarciu** [comment]
Verified as fixed : 
![twoclick](https://user-images.githubusercontent.com/1583842/27232524-0e379476-52bf-11e7-8c4c-562910f897b4.gif)

**Comment by kumar303** [comment]
Thanks for catching this bug @vcarciu !
