### ISSUE TITLE
Filter menu options change at page refresh

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3121]
Steps to reproduce:
1. Load Themes homepage https://addons-dev.allizom.org/en-US/firefox/themes/
2. Click on "More Highly Rates Themes"
3. Observe Filter menu
4. Refresh the page

Expected results:
Filter menu stays the same.

Actual results:
Filter menu options change.

Notes/Issues:
- reproducing on other pages like: search results from homepage, "More Highly Rates Extensions", "More Popular Themes", "More Popular Extensions".
- wherever you are filters turn in to "Relevance", "Extensions", "Windows" not mater what.

Verified on AMO-dev FF55(Win 7). Not reproducing on device.
For the Type option of Filter menu - the issue is also reproducing on prod.

Video for this issue:
![change](https://user-images.githubusercontent.com/15685960/30385273-570695e0-98af-11e7-80da-b5f315610687.gif)

**Comment by muffinresearch** [comment]
I've nominated this for mvp-polish but if it's more difficult that it seems them we can move this into post-release instead.

**Comment by tofumatt** [comment]
I was curious why this would be happening... I think it's actually been fixed with search tweaks but I cannot reproduce this issue.

**Comment by ValentinaPC** [comment]
This is not fixed.
Verified it on AMO-dev FF56(Win 7).
Options from Filter menu change at page refresh.
Please see video:
![filter](https://user-images.githubusercontent.com/15685960/31607084-afc0df28-b273-11e7-9339-d729780e9ef5.gif)

**Comment by ValentinaPC** [comment]
Verified as fixed on AMO-dev FF56(Win 7) in all pages that contain the Filter menu.
Postfix video:
![filter](https://user-images.githubusercontent.com/15685960/31672438-3e0ba47e-b365-11e7-8395-6fac72fc6644.gif)
