### ISSUE TITLE
Add-on cannot be installed second time if removed from about:addons after first install

### ISSUE THREAD

**Issue by ValentinaPC** [mozilla/addons-frontend#3196]
Steps to reproduce:
1. Load any webext details page i.e. https://addons-dev.allizom.org/en-US/firefox/addon/webext/
2. Install the add-on by clicking on the switch button
3. Go to about:addons - Extensions tab and click Remove for the installed add-on
4. Go back to AMO and try to install the add-on again

Expected results:
Add-on is installed.

Actual results:
Add-on cannot be installed.

Notes/Issues:
- refreshing the about:addons page will fix the issue.
- not reproducing for old AMO pages
Verified on AMO-dev FF57(Win 7).
Video for this issue:
![refresh](https://user-images.githubusercontent.com/15685960/30692988-55159074-9ed6-11e7-93de-d66c06abf5a2.gif)

**Comment by tofumatt** [comment]
Can you please attach some console log output for this?

**Comment by ValentinaPC** [comment]
Console log:
`[disco] addon found with no compatibility info for valid clientApp Object { addon: Object, clientApp: "firefox" } disco-2a8e626f40409818f080.js:1:51553`
and message details: https://pastebin.com/SryzZgr3

**Comment by muffinresearch** [comment]
This also potentially be a browser bug - we'll need to understand if the events for uninstall are not being seen by the page when you're making changes in the disco pane. Maybe multi-process has an impact on that?

**Comment by muffinresearch** [comment]
This needs investigation - first I thought this might be a browser issue but the screencast shows that the uninstall events are received on AMO. Something isn't right in the state if the uninstall is reflected on the site but a re-install is prevented.

**Comment by willdurand** [comment]
I believe this has been fixed by the new install button (`AMInstallButton`).

**Comment by AlexandraMoga** [comment]
@willdurand the `AMInstallButton` didn't quite fix the issue, as in you are still not able to re-install an extension in AMO after having removed it from about:addons without first refreshing either one of the two pages.
However, I found your comment in https://github.com/mozilla/addons-frontend/issues/5929#issuecomment-416561371 which states that this behavior can't be overcome.

**Comment by willdurand** [comment]
>  However, I found your comment in [#5929 (comment)](https://github.com/mozilla/addons-frontend/issues/5929#issuecomment-416561371) which states that this behavior can't be overcome.

correct, so it's a wontfix. Thanks for double-checking!
