### ISSUE TITLE
Expose more properties for theme install

### ISSUE THREAD

**Issue by wagnerand** [mozilla/addons-frontend#3798]
For themes, we only expose a fraction of properties compared to what we used to in the old frontend.

Example: https://addons.mozilla.org/en-US/firefox/addon/pixel-bears/ , see property `data-browsertheme` of the install button.

**For QA**: please test for regressions related to all theme functionality. This includes theme detail pages, previewing, and installation in both AMO and the Discovery Pane.

Old frontend:
```
"accentcolor": "#"
"author": "Star_Shine"
"category": "Other"
"description": ""
"detailURL": "https://addons.mozilla.org/en-US/firefox/addon/pixel-bears/"
"footer": "https://addons.cdn.mozilla.net/user-media/addons/357219/2.jpg?1326075809"
"footerURL": "https://addons.cdn.mozilla.net/user-media/addons/357219/2.jpg?1326075809"
"header": "https://addons.cdn.mozilla.net/user-media/addons/357219/Myhellokitty.jpg?1326075809"
"headerURL": "https://addons.cdn.mozilla.net/user-media/addons/357219/Myhellokitty.jpg?1326075809"
"iconURL": "https://addons.cdn.mozilla.net/user-media/addons/357219/preview_small.jpg?1326075809"
"id": "357219"
"name": "Pixel bears"
"previewURL": "https://addons.cdn.mozilla.net/user-media/addons/357219/preview_large.jpg?1326075809"
"textcolor": "#ffffff"
"updateURL": "https://versioncheck.addons.mozilla.org/en-US/themes/update-check/357219"
"version": "1.0"
```

New frontend:
```
"accentcolor": "#"
"author": "Star_Shine"
"description": null
"footerURL": "https://addons.cdn.mozilla.net/user-media/addons/357219/2.jpg?1326075809"
"headerURL": "https://addons.cdn.mozilla.net/user-media/addons/357219/Myhellokitty.jpg?1326075809"
"id": "357219"
"name": "Pixel bears"
"textcolor": "#ffffff"
```

As far as I can see, this data is used by Firefox, for example to set the favicon in the Add-ons Manager and to set the updateURL, which is important for static themes.
Optimally, we would expose the same properties as in the old frontend.

Marking P2 on @jvillalobos' request.

**Comment by kumar303** [comment]
Ah, yes, this slipped through the cracks somehow. I thought we had a bug on file for the disappearing icon behavior but I can't find it.

**Comment by kumar303** [comment]
> the disappearing icon behavior

This might have been fixed. I could not reproduce any scenario where installing a theme does not add an icon to the add-on manager.

**Comment by ValentinaPC** [comment]
> For QA: please test for regressions related to all theme functionality. This includes theme detail pages, previewing, and installation in both AMO and the Discovery Pane.

- we are talking about static themes, yes?

> This might have been fixed. I could not reproduce any scenario where installing a theme does not add an icon to the add-on manager.

 - what icon do you talk about? this one:
![2017-11-08_1209](https://user-images.githubusercontent.com/15685960/32543248-c211a538-c47d-11e7-9190-0597ad3ee5dd.png)

**Comment by wagnerand** [comment]
> This might have been fixed. I could not reproduce any scenario where installing a theme does not add an icon to the add-on manager.

@kumar303 I can still reproduce.

STR using example: https://addons.mozilla.org/en-US/firefox/addon/xmas-02-paillette/
1. Install using the old frontend:
![screen shot 2017-11-08 at 11 33 46](https://user-images.githubusercontent.com/873258/32544436-c65aff2c-c478-11e7-89c8-e1cb4e96e700.png)
2. Go to the Add-ons Manager
![screen shot 2017-11-08 at 11 35 00](https://user-images.githubusercontent.com/873258/32544472-e0dc7e16-c478-11e7-9891-8f1ff7f7748e.png)

vs.

1. Install using the new frontend:
![screen shot 2017-11-08 at 11 35 37](https://user-images.githubusercontent.com/873258/32544510-f70ea132-c478-11e7-8b7d-1336890f5694.png)
2. Go to the Add-ons Manager
![screen shot 2017-11-08 at 11 35 54](https://user-images.githubusercontent.com/873258/32544525-00ed8d26-c479-11e7-9157-211d8a12b483.png)

@ValentinaPC 
> we are talking about static themes, yes?

For now, we don't. Eventually, it should be supported when static themes are ready too.

> what icon do you talk about? this one:
Yes, the icon in the Add-ons Manager; also see above screenshots.

**Comment by ValentinaPC** [comment]
I was also able to reproduce the "icon" issue from Disco Pane also.
Used theme: https://addons-dev.allizom.org/en-US/firefox/addon/all-fall/

Also there was a Bugzilla issue initially logged for this icon thing:
https://bugzilla.mozilla.org/show_bug.cgi?id=1393361
Then Andrew logged a github one
- https://github.com/mozilla/addons-server/issues/6261
And I transfered to the right repository at the end:
- https://github.com/mozilla/addons-frontend/issues/3014

**Comment by wagnerand** [comment]
@ValentinaPC Ah, thank you. I didn't see that other bug, sorry. Maybe let's close that one since this one already got a PR attached?

**Comment by kumar303** [comment]
> I thought we had a bug on file for the disappearing icon behavior but I can't find it.

found it https://github.com/mozilla/addons-frontend/issues/3014 :)

**Comment by ValentinaPC** [comment]
> found it #3014 :)

Me2 :)

**Comment by ValentinaPC** [comment]
> For QA: please test for regressions related to all theme functionality. This includes theme detail pages, previewing, and installation in both AMO and the Discovery Pane.

Verified this on AMO-dev FF58(Win 7).
1. Postfix video related to theme icon after install -  works as expected
![disco-pane](https://user-images.githubusercontent.com/15685960/32729002-0dac7fca-c88b-11e7-843c-78decdbd899d.gif)

2. Description is not displayed if the theme is installed from Disco Pane, and is displayed if installed from AMO-new frontend

What do you think about 2?

**Comment by kumar303** [comment]
> Description is not displayed if the theme is installed from Disco Pane, and is displayed if installed from AMO-new frontend

Good catch, please file a new bug. I think this bug always existed -- I have a suspicious of what the cause is.

**Comment by ValentinaPC** [comment]
@kumar303 : I only found this issue - https://bugzilla.mozilla.org/show_bug.cgi?id=1263610 -  with dupe in GitHub - https://github.com/mozilla/addons-server/issues/3055 .

Will log a separate issue for description part.
