### ISSUE TITLE
Broken link from mozilla privacy campaign

### ISSUE THREAD

**Issue by kenrin** [mozilla/addons-frontend#3920]
### Describe the problem and steps to reproduce it:

The link https://addons.mozilla.org/firefox/collections/mozilla/privacy/ is broken.  I followed the link from the website https://www.mozilla.org/en-US/teach/smarton/tracking/ which was one of the start page privacy information links.

### What did you expect to happen?
I expected it to take me to a collection of mozilla privacy addons and it took me to a broken page to report the issue.

**Comment by wagnerand** [comment]
@devaneymoz did we delete that collection?

**Comment by kumar303** [comment]
@kenrin thanks for the bug report.

Hi @jpetto do you know anything about this link?

I'm marking this as high priority since it's a highly visible 404. The link appears here:

<img width="273" alt="screenshot 2017-11-15 17 03 43" src="https://user-images.githubusercontent.com/55398/32865022-ff102bb8-ca26-11e7-885d-3c70e848e120.png">

**Comment by jpetto** [comment]
I know those SmartOn pages are pretty old, and that it's relatively easy to update the link. 😁 What URL should we point it to?

**Comment by wagnerand** [comment]
I have found https://addons.mozilla.org/en-US/firefox/collections/mozilla/privacy-matters/ which could be the one, but @devaneymoz should confirm.

**Comment by wagnerand** [comment]
Also, for the record, we could also update the slug on our end to be *.../privacy* if we want that.

**Comment by devaneymoz** [comment]
Thank you for raising this issue! The title of the collection recently changed, and automatically altered the slug. My preferred fix would be to update the mozilla.org page with the new URL (   /privacy-matters/   ), since other areas including AMO homepage point to the new URL. 

Can we do that?

**Comment by jpetto** [comment]
We can update the URL to anything you'd like. Should it be updated to the following?

https://addons.mozilla.org/firefox/collections/mozilla/privacy-matters/

**Comment by willdurand** [comment]
@jpetto yes

**Comment by muffinresearch** [comment]
@bqbn would it be possible to setup a 301 redirect in nginx for both:

`/%locale%/firefox/collections/mozilla/privacy/` -> `/%locale%/firefox/collections/mozilla/privacy-matters/` where `%locale%` represents any locale e.g. `en-US`.
`/firefox/collections/mozilla/privacy/` -> `/firefox/collections/mozilla/privacy-matters/` this is a non-locale prefixed link which saves hitting the app first to get a country code to then do the first redirect.

Doing this at the nginx level makes sense since this impacts both the old and new site. We can't change the slug and it would be good to have a redirect in place in case of additional backlinks and bookmarks.

**Comment by kumar303** [comment]
Do we still need to set up the redirects? https://www.mozilla.org/en-US/ has been fixed with the correct link in https://github.com/mozilla/bedrock/pull/5292 (thanks @jpetto !)

**Comment by willdurand** [comment]
Maybe this collection is linked in other places too? If it is an important collection, that would be still worthwhile.

**Comment by jpetto** [comment]
On moz.org, we generally do set up redirects for this kind of thing. You never know how many links might be out there.

**Comment by muffinresearch** [comment]
Example Urls to test on -dev:

- https://addons-dev.allizom.org/firefox/collections/mozilla/privacy/
- https://addons-dev.allizom.org/android/collections/mozilla/privacy/
- https://addons-dev.allizom.org/en-US/firefox/collections/mozilla/privacy/
- https://addons-dev.allizom.org/en-US/android/collections/mozilla/privacy/
- https://addons-dev.allizom.org/fr/firefox/collections/mozilla/privacy/
- https://addons-dev.allizom.org/fr/android/collections/mozilla/privacy/ 

Example Urls to test on stage:

- https://addons.allizom.org/firefox/collections/mozilla/privacy/
- https://addons.allizom.org/android/collections/mozilla/privacy/
- https://addons.allizom.org/en-US/firefox/collections/mozilla/privacy/
- https://addons.allizom.org/en-US/android/collections/mozilla/privacy/
- https://addons.allizom.org/fr/firefox/collections/mozilla/privacy/
- https://addons.allizom.org/fr/android/collections/mozilla/privacy/

**Comment by muffinresearch** [comment]
We pushed a redir into prod so this should be fixed now and when the link updates it should save the 301.

**Comment by ValentinaPC** [comment]
> The link https://addons.mozilla.org/firefox/collections/mozilla/privacy/ is broken

Seems like the link is working now. Is there anything else we should be checking here?

I've also made a collection private, and logged out from AMO, and I can still see collection listing page. (i.e. Bookmarks collection). Is this ok?

**Comment by willdurand** [comment]
> Seems like the link is working now. Is there anything else we should be checking here?

I think it is all goos then.

**Comment by ValentinaPC** [comment]
Marking this verified fixed.
Private collection issue is tracked separately.
