### ISSUE TITLE
A glitch appears for a moment after save collection button is clicked

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#4729]
STR:
1. Load AMO dev and go to View My Collections.
2. Choose an existing collection **without any add-ons** and click Edit this collection link.
3. Click the save collection button.
4. Observe the screen.

Expected result:
Collection's page is displayed.

Actual result:
Before the page is displayed a glitch appears for a short moment.

Notes:
This is reproducible on AMO dev with FF59 (Win10). 

![glitch](https://user-images.githubusercontent.com/33448286/38306263-af02852a-3818-11e8-867a-715d75691eb6.gif)

**Comment by bobsilverberg** [comment]
What's happening here is the following:

1. After updating the collection we invalidate it in the cache, so the new values will be picked up the next time it is fetched.
2. We then redirect to the collection screen.
3. The collection screen loads, and displays the loading placeholders for add-ons in the collection while the collection is fetched in the background. This is the flash of content that is seen.
4. Once the collection is loaded into the cache, the screen updates, removing the loading placeholders, which is the flash of disappearing content, and also causes the screen size to change because there are fewer add-ons displayed (in the case above there are none).

Note that one will likely still see this flash of content when loading a collection for the first time which has fewer add-ons than the number of placeholders.

There are a couple of different things we could do here:
1. We could try changing the screen a bit to minimize the impact of the flash of content by reducing the number of placeholder add-ons, so that the screen size is unlikely to change. Also, it will be a lot less jarring if the number of placeholders is less than or equal to the number of add-ons actually in the collection, so that's probably a worthwhile change to make. This could help this situation, and also the general one of loading a collection for the first time.
2. We could, as part of the update workflow, load the updated collection into the cache before re-directing to the collection screen, which _should_ avoid the need to fetch it and therefore avoid displaying and removing the placeholders.

I'm going to experiment a bit with #1 above to see how much I can improve the situation.

@tofumatt Do you have any thoughts or opinions on the above?

**Comment by bobsilverberg** [comment]
Note also that this is not a regression caused by #4505, but something that would have existed prior to that.

**Comment by bobsilverberg** [comment]
Now that we've changed the workflow so that we leave the user on the edit screen after creating a collection, I think this is no longer an issue. @ioanarusiczki could you verify whether this is still reproducible?

**Comment by bobsilverberg** [comment]
I believe this will be fully addressed by #5673.

**Comment by kumar303** [comment]
I believe this is fixed by https://github.com/mozilla/addons-frontend/issues/5672 but if not, let me know.

**Comment by AlexandraMoga** [comment]
@kumar303 it seems that #5673 has not fixed this issue after all:

![small glitch](https://user-images.githubusercontent.com/31961530/43072101-91753456-8e7d-11e8-965b-34b0e5bcabbd.gif)

**Comment by bobsilverberg** [comment]
That's actually expected. If we want to fix this case entirely, then we'll have to let the Collection Edit screen know that we've just finished creating a collection, and use that information to not display the loading indicators on the right-hand side.

Do you think that's something worth implementing @kumar303?

**Comment by kumar303** [comment]
@AlexandraMoga thanks for the screencast. 

I looked at the original screencast for this issue and I believe that the STR were not accurate. I just edited them now to point out that this only happens when you edit a collection *without* any add-ons. 

So, yes, with that updated STR this issue is not fixed.

However, if you were to edit an existing collection with a small number of add-ons *before* #5673 was fixed then you would have seen what looks like a momentary glitch. Now that #5673 has landed, it won't look like much of a glitch anymore since the number of loading add-ons will match the number of add-ons in the collection.

With the updated STR, I don't think it's worth fixing this issue. It is very unlikely that a user will be editing a collection without any add-ons 😁 

I am closing this issue but feel free to comment here if I've misunderstood something.

**Comment by AlexandraMoga** [comment]
With the updated STR, the issue is indeed invalid, also taking in consideration that #5635 has landed, which makes the steps impossible to reproduce. 

I can confirm also that with #5673 the screen will only load the number of add-ons existing in the collection (not the whole screen).
