### ISSUE TITLE
Chrome can't load cached responses for statics when missing CORS headers

### ISSUE THREAD

**Issue by muffinresearch** [mozilla/addons-frontend#5825]
On chrome, I've sometimes seen an issue where the CSS isn't loaded. Looking at the responses for the CSS there's no CORS headers in the response:

```
Age: 583098
Cache-Control: max-age=315360000, immutable
Connection: keep-alive
Date: Thu, 02 Aug 2018 10:35:25 GMT
Expires: Wed, 26 Jul 2028 16:23:50 GMT
Server: AmazonS3
Vary: Accept-Encoding
Via: 1.1 c31d49af55fff364fbd11e21a32f7fcb.cloudfront.net (CloudFront)
X-Amz-Cf-Id: 4XuBVKTsYSjZMOP4N-D6BKMykZiFEAKmN_3qmiqDoE1cmYrzb6EeEA==
x-amz-version-id: Jx_OHlhrHy8mZwyTzxdwMZaEFoaw7Rav
X-Cache: Hit from cloudfront
```

I also see the following in the console:

```
Access to CSS stylesheet at 'https://addons-amo.cdn.mozilla.net/amo-1e82033f757cb2138991a4cf400ee756.css' from origin 'https://addons.mozilla.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://addons.mozilla.org' is therefore not allowed access.
```

Digging into this further it appears that if a cached response has no cors headers then it will fail to load the second time if CORS headers are required. 

A hard refresh fixes the issue.

I'm not sure how it gets into this state, but a way to reproduce the problem can be carried out as follows.

* Find the URL for the current CSS file loaded on addons.mozilla.org. 
* Load that in a new Chrome incognito window to prevent existing caches messing things up (It's the same origin (the CDN's) so no CORS headers will be in the response) 
* This file will then be cached
* Now request AMO from https://addons.mozilla.org (different origin need CORS to load for SRI) 
* Note there's no CSS and the CSS load was denied.

I think to fix this we'd need to add `Vary: Origin`.

See also this bug https://bugs.chromium.org/p/chromium/issues/detail?id=409090

**Comment by autrilla** [comment]
With CloudFront, requests take the following flow:

```
User-Agent ---(1)---> CloudFront ---(2)---> S3 ---(3)---> CloudFront ---(4)---> User-Agent
```

We have several options:

- CloudFront lets us easily set HTTP headers at `(2)`. In dev, I've manually added `Origin: https://addons-dev.allizom.org/` as a header. This makes S3 include CORS headers in the response, even if the User-Agent doesn't send an `Origin` header. It's a pretty ugly solution, but it works fine. We could set any origin (at least right now) because we allow `*`.

- We could set HTTP headers at `(3)` by proxying S3 with nginx, but this means we need an extra load balancer and EC2 instances. I estimate a couple days of work to get this fully set up.

- We could also set up a Lambda@Edge function to set HTTP headers at any point. This shouldn't have a huge impact on cost, but it'd probably also take a couple of days of work or so.

I think the first option is the best right now. If you disagree, please let me know and I can work on any of the other options. If you agree, I'll add option 1 to our automation.

**Comment by muffinresearch** [comment]
@psiinon I'd also welcome any input you have on the solution being proposed for this issue (Setting origin in the requests) - I don't see any security implications but I'd welcome a quick sanity check.

**Comment by psiinon** [comment]
I've fine with this just being added tp static resources from the CDN.

**Comment by willdurand** [comment]
moving this issue to next milestone

**Comment by ioanarusiczki** [comment]
I verified this with the steps given by @muffinresearch  Chrome - Version 68.0.3440.106

on AMO dev - I did not receive the css error, page loaded without problems 

![amo dev](https://user-images.githubusercontent.com/33448286/44993115-1794f180-afa2-11e8-880c-5a9c4ddcd254.png)

this is  AMO prod - the error is there. Means it's fixed now.

![amo prod](https://user-images.githubusercontent.com/33448286/44993144-32fffc80-afa2-11e8-8718-1f1021c9eb56.png)

**Comment by bqbn** [comment]
The fix in https://github.com/mozilla-services/cloudops-deployment/pull/2451 has just been applied to -stage. Please test.

**Comment by ioanarusiczki** [comment]
The issue is now reproducible on AMO stage with FF62(Win10). Not reproducible on AMO dev (re-checked it).

Please take a look - AMO stage
![css not loading on stage](https://user-images.githubusercontent.com/33448286/45155112-88c2e780-b1e2-11e8-8f2b-907ffc4fa909.png)

Also, I receive 504 errors on Chrome too with AMO stage (not reproducible on -dev). An issue is logged here https://github.com/mozilla/addons-server/issues/9363

**Comment by bqbn** [comment]
Please re-test now that https://github.com/mozilla/addons-server/issues/9363 is fixed. 

I suspect the 504 you saw on -stage regarding this issue is ephemeral.

**Comment by ioanarusiczki** [comment]
@bqbn 

Tested this again for -stage and -prod and it is still reproducible. 

![css not loaded with chrome incognito](https://user-images.githubusercontent.com/33448286/45207932-0560cf00-b292-11e8-9e93-21c4d2e64c76.gif)

**Comment by bqbn** [comment]
@ioanarusiczki I can't re-produce it on -stage. Can you describe the steps how you can reproduce it, so I can follow and see?

https://github.com/mozilla-services/cloudops-deployment/pull/2451 hasn't been applied to -prod yet. So no need to test -prod at this point.

**Comment by ioanarusiczki** [comment]
@bqbn I tested it again today. This morning it worked, but later I tried again and it is still reproducible together with https://github.com/mozilla/addons-server/issues/9379 
I think they're related issues and both seem to be intermittent. 

For Chrome what I did:
1. Opened a Chrome incognito window and pasted the current URL of the CSS file into the first tab.
2. The I open a new tab and try to access AMO stage https://addons.allizom.org/en-US/firefox/

**Comment by muffinresearch** [comment]
@ioanarusiczki make sure the CDN css is loaded busting any previous cache e.g. with a hard refresh. For me testing on stage the fix works whereas prod (which doesn't have the fix) is still broken.

Simplified STR:

_Note: CDN links are correct at time of testing if in doubt grab the links loaded by the page when testing._

Stage:

* Load https://addons-amo-cdn.allizom.org/amo-642264cdd35b16d4c928692a85685bfe.css in chrome and force refresh the page to ensure it's not cached.
* Visit https://addons.allizom.org/en-GB/firefox/ and see CSS is loaded fine

Prod (before the fix):

* Load https://addons-amo.cdn.mozilla.net/amo-36f72c5ded66fcddf74acb804d0298ae.css in chrome and force refresh the page to ensure it's not cached.
* Visit https://addons.mozilla.org/en-GB/firefox/ and note there's no CSS.

**Comment by muffinresearch** [comment]
I'm closing this issue on the basis it is working on stage. Just need QA to re-validate.

**Comment by kumar303** [comment]
FYI: this change triggered a couple minutes of downtime in production for some users (on multiple browsers) while the deployment of https://github.com/mozilla-services/cloudops-deployment/pull/2451 was pushed to the CDN ahead of code deployment.
