### ISSUE TITLE
"Log in to rate this …" offset in Firefox ESR 52.9.0 and Waterfox

### ISSUE THREAD

**Issue by grahamperrin** [mozilla/addons-frontend#6357]
For example: 

![2018-09-22 01 57 25 terminals](https://user-images.githubusercontent.com/192271/45911598-64375400-be0d-11e8-8777-3d0ff6698710.png)

– Waterfox 56.2.3 on FreeBSD-CURRENT, with a new profile. 

Affecting pages such as https://addons.mozilla.org/addon/loremizer/ 

Not reproducible in Firefox, Chromium, Surf or Web. 

Layout in browsers such as Falkon is quite different but (at a glance) not comparably bugged.

**Comment by grahamperrin** [comment]
Thanks, 

> … unfortunately I don't think the devs here can help …

OK, spun off to the support area at https://redd.it/9jv6lj 

----

As a side note, 

> … Waterfox is separate from Firefox :slightly_frowning_face:  …

That dis-association in the web site footer is, I think, a bit too terse and/or (UPPERCASE) shouty. Maybe interpreted as rage against Mozilla (in which case, I can understand people frowning) but honestly, I don't sense rage. Recently at <https://www.reddit.com/comments/9dc129/-/e5hrjje/> the founder wrote: 

>> … assumption that developing Waterfox automatically makes me anti-Mozilla 🤷‍♂️. Quite the opposite. I have nothing but respect for Mozilla …

FWIW I reckon, that part of the footer is (partly) to discourage users of Waterfox from seeking Waterfox-specific help in Mozilla support areas.

**Comment by willdurand** [comment]
@grahamperrin we merged a fix recently, is it better now? (can you try on addons-dev.allizom.org?)

**Comment by grahamperrin** [comment]
First load of a page: not fixed, when I reloaded that particular page it appeared to be fixed but after that, all other pages that I tested seem to be not fixed (sorry). 

The button briefly 'slides' into place but after a split-second, it reverts to the left. 

Screen recording available on request. 

Thanks for your attention to this :-)

**Comment by willdurand** [comment]
> Screen recording available on request.

I'd be interested in that yep, thanks!

**Comment by grahamperrin** [comment]
Screen recording: [2018-10-17 17:46.mp4.zip](https://github.com/mozilla/addons-frontend/files/2497925/2018-10-17.17.46.mp4.zip)

**Comment by willdurand** [comment]
Thanks for your very first contribution @HosseinMarzban! /cc @caitmuenster

**Comment by SeanPrashad** [comment]
Also if you're wondering why I'm showing up in the commits, I helped @HosseinMarzban clean up the commits in his PR as it covered two issues instead of one - he implemented this patch all on his own!

**Comment by ioanarusiczki** [comment]
Verified on Firefox ESR 52.9.0 and Waterfox 56.2.5 on Windows 10 and mac OS10.13.6

here's the FF ESR with Win10 - what's now in prod and then the fix

![ff esr before and after](https://user-images.githubusercontent.com/33448286/48545261-3252e300-e8ce-11e8-9c83-9828fa91349d.gif)

**Comment by grahamperrin** [comment]
Fix verified with Waterfox 56.2.6 on FreeBSD-CURRENT. Thanks!
