### ISSUE TITLE
Non public notices no longer display on product detail pages for admin users 

### ISSUE THREAD

**Issue by rebmullin** [mozilla/addons-frontend#6944]
### Describe the problem and steps to reproduce it:

Find a non public addon

### What happened?

We get a server error 

appears logged out (I am not sure but maybe this is expected)

### What did you expect to happen?

We used to see notices if they were seeing this page as an admin (requested in #4244)

for non admins, maybe a 404 should be displayed?

Regarding the notices, this is what we used to see:
![Alt text](https://monosnap.com/image/IUHPq5oN21JT0if42LJrXrO03wxz4W.png)

again now we see:
https://addons-dev.allizom.org/en-US/firefox/addon/rm2-magon-worpier-roose/

I am not sure if this regression or possibly a deliberate change

**Comment by willdurand** [comment]
That looks related to the versions change. /cc @bsilverberg

**Comment by willdurand** [comment]
That looks related to the versions change. /cc @bobsilverberg

It's probably not a papercut, and likely a p2.

**Comment by willdurand** [comment]
I see the error in Sentry: https://sentry.prod.mozaws.net/operations/addons-frontend-amo-dev/issues/4925308/?query=is:unresolved. I believe that's because we make the assumption that an `addon` always has a `currentVersionId` in the `mapStateToProps()` function of the `Addon` component.

**Comment by rebmullin** [comment]
thanks for all the info @willdurand ++

The reason I put it as a p4 was because that was the initial p level for the original request so I figured it would be the same. Especially since it's only for admin users. Altho I am not sure what non admin users should be seeing. I guess we can see what @bobsilverberg thinks about this.

**Comment by willdurand** [comment]
> Altho I am not sure what non admin users should be seeing.

Non-admin users will see a 404 (and it still works) so this is OK at least.

**Comment by bobsilverberg** [comment]
> I believe that's because we make the assumption that an `addon` always has a `currentVersionId` in the `mapStateToProps()` function of the `Addon` component.

Yeah, we shouldn't be doing that. I know there was some back and forth about this in some reviews, but an addon can exist without a version, so we cannot assume one exists.

I'll fix the code in `mapStateToProps` and that should fix this.

**Comment by ioanarusiczki** [comment]
@rebmullin Could you please tell the exact scenario for the server error display? 

I tried like this (with same results on AMO dev and AMO stage): with an Admin account I went and disabled all versions of the add-on but then the view listing page is not available so I had to re-enable one version (here's when issue https://github.com/mozilla/addons-server/issues/3051 occurs, because the "Incomplete" status for the add-on persists) then I clicked the detail page of the add-on and could see it's content and the red warnings. 

![the elevated permissions](https://user-images.githubusercontent.com/33448286/48627390-26921a00-e9bd-11e8-9229-22d73fb6e600.gif)

Also when an add-on is submitted and not auto-approved yet I get the same results. The page is displayed and the messages too.

**Comment by ioanarusiczki** [comment]
@bobsilverberg @willdurand

The only scenario where this is still reproducible is when all versions are disabled from dev hub by the developer - the add-on detail page is no longer displayed in this case. I think this was not covered in https://github.com/mozilla/addons-frontend/issues/4244 where I tested with disabling the add-on from rev tools by an admin. 
So , I filed https://github.com/mozilla/addons-frontend/issues/6976
