### ISSUE TITLE
broken CSS - AMO dev and Disco Pane dev won't load correctly 

### ISSUE THREAD

**Issue by ioanarusiczki** [mozilla/addons-frontend#7396]
STR:
1. Open a new profile and load AMO dev and Disco Pane dev

Expected result:
The pages load correctly.

Actual result:
CSS is not loading correctly.

Notes:
Reproducible only with AMO dev and Disco Pane dev FF64(Win10). 
It's also reproducible on old profiles.

![broken css](https://user-images.githubusercontent.com/33448286/51189956-db778300-18e9-11e9-9733-e411e15a2bb1.png)

**Comment by willdurand** [comment]
This happened because of a deployment. It should be fixed by itself now.

**Comment by kumar303** [comment]
I filed a more specific bug for ops: https://bugzilla.mozilla.org/show_bug.cgi?id=1520231

**Comment by kumar303** [comment]
This has been fixed by @autrilla 🙏 

See https://bugzilla.mozilla.org/show_bug.cgi?id=1520231

**Comment by ioanarusiczki** [comment]
I can reproduce it on AMO Dev only - with Disco Pane - old and new profile, FF64 (Win10).

![still reproducible1](https://user-images.githubusercontent.com/33448286/51241907-783c2e00-1987-11e9-98a3-906399102313.gif)

**Comment by autrilla** [comment]
Forgot to update the cert for discopane. Should be good now.

**Comment by ioanarusiczki** [comment]
@autrilla Yes, it's fixed now, I tested with FF64 (win10) - new and old profiles, disco pane and AMO dev are loading correctly.
