### ISSUE TITLE
Wrong Link to Dictionary for Hindi Language

### ISSUE THREAD

**Issue by championshuttler** [mozilla/addons-frontend#7702]
### Describe the problem and steps to reproduce it:

Go to https://addons.mozilla.org/en-US/firefox/language-tools/

### What happened?

Check the Dictionary listed for Hindi Language, right now its Hiligaynon spell checker which is wrong

### What did you expect to happen?

Correct Dictionary for Hindi Language should be listed.

### Anything else we should know?

![image](https://user-images.githubusercontent.com/22130317/53736782-be563e00-3eb0-11e9-9a79-3f6e0359e9cd.png)

**Comment by suhailsinghbains** [comment]
Hi @championshuttler Can I please work on this?
Thanks

**Comment by willdurand** [comment]
The issue is related to the regex used to match languages variants that is too permissive. Here is a quick fix for this issue:

```diff
diff --git a/src/amo/pages/LanguageTools/index.js b/src/amo/pages/LanguageTools/index.js
index 50cb73ebf..dd499d083 100644
--- a/src/amo/pages/LanguageTools/index.js
+++ b/src/amo/pages/LanguageTools/index.js
@@ -200,7 +200,7 @@ export class LanguageToolsBase extends React.Component<Props> {
                       return addon.target_locale === language.locale;
                     }
 
-                    const re = new RegExp(`${language.locale}(-\\w+)?`);
+                    const re = new RegExp(`^${language.locale}(-\\w+)?$`);
 
                     return addon.target_locale && re.test(addon.target_locale);
                   });
```

**Comment by makkBit** [comment]
I am working on this. will submit a PR soon.

**Comment by caitmuenster** [comment]
Mentor: @willdurand

**Comment by Shubhamchinda** [comment]
Can I take up this bug?

**Comment by willdurand** [comment]
@Shubhamchinda yep

**Comment by suhailsinghbains** [comment]
Hi @Shubhamchinda 
Please go on, [Getting Started](https://github.com/mozilla/addons-frontend#get-started) this will help you in setting up the project, if you have any issues, feel free to ask :)

**Comment by sashaktpathak** [comment]
Hi, if anybody has not taken up this issue. Can i work on it. I read that @willdurand asked to create a  test case for this issue. Can anybody tell me how to create one.

**Comment by Shubhamchinda** [comment]
@willdurand Okay, Thanks I'll write the test case and let you know when it's done.
Thanks @suhailsinghbains .

**Comment by suhailsinghbains** [comment]
Hi @sashaktpathak Shubhamchinda is working on this, so, it cannot be transfered to you without consent. Please feel free to go [issues](https://github.com/mozilla/addons-frontend/issues?q=is%3Aissue+is%3Aopen+label%3A%22contrib%3A+welcome%22)

**Comment by Shubhamchinda** [comment]
@willdurand Can take a look at it?

**Comment by willdurand** [comment]
> @willdurand Can you please take a look at it?

I am not sure I understand the test case you wrote. Could you explain it to me? The test case should fail in any case, given that the issue should be fixed. Thanks!

**Comment by Shubhamchinda** [comment]
@willdurand I worked on it again, I hope I did it correct this time. Let me know if its' still not correct.

**Comment by ioanarusiczki** [comment]
@willdurand Right now -dev and -stage have a Hindi(India) dictionary available. 

![only one Hindi](https://user-images.githubusercontent.com/33448286/60598410-5871b880-9db5-11e9-99dd-bff3dc97b059.png)


I believe this needs a check after it lands on prod.

**Comment by willdurand** [comment]
> I believe this needs a check after it lands on prod.

@ioanarusiczki that looks good. I suppose we could upload the Hiligaynon spell checker in -dev/stage and make sure it does not appear here.

**Comment by ioanarusiczki** [comment]
@willdurand It's one Hindi now on prod which takes users to `Hindi Spell Checker`

![only one hindi](https://user-images.githubusercontent.com/33448286/60711125-d9978f80-9f1c-11e9-8d1e-9e203510c162.gif)
