### ISSUE TITLE
addons.mozilla.org has failed the web security baseline

### ISSUE THREAD

**Issue by moz-hwine** [mozilla/addons-frontend#8957]
Site https://addons.mozilla.org has failed the web security baseline scan.

The failing tests are:

 Cookie No HttpOnly Flag [10010] x 1 
 * https://addons.allizom.org/en-US/firefox/addon/ublock-origin/?src=homepage-primary-hero (200 OK)

 Cookie Without Secure Flag [10011] x 1 
 * https://addons.allizom.org/en-US/firefox/addon/ublock-origin/?src=homepage-primary-hero (200 OK)

This issue was automatically raised.

This issue is managed automatically by the baseline scan:

 * If the failing tests change then it will be updated
 * If it is closed before the tests pass then a new one will be opened
 * When all of the tests pass then it will be closed

Full details, including how to test for these issues locally, can be found on this [Security Baseline Service](https://sql.telemetry.mozilla.org/dashboard/security-baseline-service-latest?p_w53332_site_60280=addons.mozilla.org) dashboard.
If you have any questions or concerns please get in contact with @psiinon

**Comment by willdurand** [comment]
@psiinon is the mismatch between the domain in the title (-prod environment) and the actual URL that has been scanned (-stage) intended?

**Comment by willdurand** [comment]
I think the issue is the same as #8958 (a new cookie has been added for a A/B experiment).

**Comment by bobsilverberg** [comment]
#8958 should be fixed via #8962, but this one needs to be addressed. As @willdurand mentioned in #8958, I don't think we can set the cookie to be `HttpOnly` because we need to access it via the React app, but we could change it to be a secure cookie though.

@psiinon Is there something we can do to indicate that the exclusion of `HttpOnly` is intentional for this cookie so that this failure does not continue to be triggered?

**Comment by moz-hwine** [comment]
The web security baseline for site https://addons.mozilla.org is still failing, this issue should stay open.

**Comment by bobsilverberg** [comment]
> The web security baseline for site [addons.mozilla.org](https://addons.mozilla.org) is still failing, this issue should stay open.

Oops, sorry. #9002, combined with the whitelisting that @psiinon is going to do should fix this, but that hasn't been deployed to prod yet. I forgot that merging #9002 would automatically close this issue.

**Comment by moz-hwine** [comment]
The following test(s) for site https://addons.mozilla.org have now passed:

 * Cookie Without Secure Flag

Keep up the good work!

**Comment by moz-hwine** [comment]
The web security baseline for site https://addons.mozilla.org is still failing, this issue should stay open.

**Comment by psiinon** [comment]
FYI as per https://github.com/mozilla/addons-frontend/issues/8957#issue-525358994 this issue is automatically managed. Its on me to whitelist this - feel free to assign it to me. Unfortunately I'm working on a high priority project and havnt had any time to focus on other things :/

**Comment by moz-hwine** [comment]
The web security baseline scan results for site https://addons.mozilla.org has new failures:


 Strict-Transport-Security Header Not Set [10035] x 1 
 * https://addons.allizom.org/en-US/firefox/collections/4757633/privacy-matters/ (504 GATEWAY_TIMEOUT)

**Comment by moz-hwine** [comment]
The following test(s) for site https://addons.mozilla.org have now passed:

 * Cookie No HttpOnly Flag

Keep up the good work!

**Comment by moz-hwine** [comment]
The web security baseline for site https://addons.mozilla.org is still failing, this issue should stay open.

**Comment by moz-hwine** [comment]
The web security baseline scan for site https://addons.mozilla.org now passes - well done team!
